### PR TITLE
Build for R 3.4.1

### LINKED ISSUE #5: Build 1.3.15 for R=3.4.1?
Currently, the available versions for r-rodbc are:
```
$ conda search r-rodbc
Loading channels: done
# Name                       Version           Build  Channel
r-rodbc                       1.3_14        r3.3.1_0  pkgs/r
r-rodbc                       1.3_14        r3.3.2_0  conda-forge
r-rodbc                       1.3_14        r3.3.2_0  pkgs/r
r-rodbc                       1.3_14        r3.4.1_0  conda-forge
r-rodbc                       1.3_14 r351h14c3975_1000  conda-forge
r-rodbc                       1.3_14  r351h470a237_0  conda-forge
r-rodbc                       1.3_15 mro343h086d26f_0  pkgs/r
r-rodbc                       1.3_15 mro350hbc2858b_0  pkgs/r
r-rodbc                       1.3_15 mro351hd10c6a6_0  pkgs/r
r-rodbc                       1.3_15        r3.4.1_0  pkgs/r
r-rodbc                       1.3_15  r342hb813f04_0  pkgs/r
r-rodbc                       1.3_15  r343h086d26f_0  pkgs/r
r-rodbc                       1.3_15  r350hb353451_0  pkgs/r
r-rodbc                       1.3_15  r351h96ca727_0  pkgs/r
r-rodbc                       1.3_15 r351h96ca727_1000  conda-forge
r-rodbc                       1.3_15  r351hc070d10_0  conda-forge
```

I'm building my whole stack from conda-forge (and need environments for both R=3.4 and R=3.5), and would need `r-rodbc>=1.3.15` also on R=3.4. I'd like to avoid having to change to defaults for this (cf. conda/conda#8533), so I was wondering if it would be possible to make a build for that combination as well?

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #5

cc @h-vetinari

### CODE REVIEW

**Comment by h-vetinari** [comment]
Hm, yeah, the C compiler seems to not be available on linux:
```
[...]
* installing to library ‘/home/conda/feedstock_root/build_artifacts/r-rodbc_1554923203159/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library’
* installing *source* package ‘RODBC’ ...
** package ‘RODBC’ successfully unpacked and MD5 sums checked
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... no
configure: error: in `/home/conda/feedstock_root/build_artifacts/r-rodbc_1554923203159/work':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR: configuration failed for package ‘RODBC’
[...]
```

**Comment by jdblischak** [comment]
> Hm, yeah, the C compiler seems to not be available on linux:

@h-vetinari Well it figures that the one platform you need to work is the only one that doesn't. Out of desperation I activated the CircleCI build, but that is unlikely to even start.

I added gcc as a build requirement, just like the old recipe used to prior to the compiler migration.

https://github.com/conda-forge/r-rodbc-feedstock/blob/87e2d5a48fabfee5d69477dba8ac075856ef4678/recipe/meta.yaml#L33

**Comment by jdblischak** [comment]
CircleCI finally ran, but it failed to even install gcc.

```
Executing transaction: ...working... ERROR:conda.core.link:An error occurred while installing package 'defaults::gcc-4.8.5-7'.
LinkError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /home/conda/feedstock_root/build_artifacts/r-rodbc_1554928667151/_build_env/bin/.gcc-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

failed
ERROR:conda.core.link:An error occurred while installing package 'defaults::gcc-4.8.5-7'.
LinkError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /home/conda/feedstock_root/build_artifacts/r-rodbc_1554928667151/_build_env/bin/.gcc-post-link.sh
==> script messages <==
<None>

Attempting to roll back.
```

https://circleci.com/gh/jdblischak/r-rodbc-feedstock/8

**Comment by dbast** [comment]
Would it help to branch away the r3.4.1 branch from an old master commit before the 3.5.1 and compiler updates? And then update this to the newest package version...

**Comment by dpryan79** [comment]
Might it help to use `linux-anvil` rather than `linux-anvil-comp7`?

**Comment by jdblischak** [comment]
> Would it help to branch away the r3.4.1 branch from an old master commit before the 3.5.1 and compiler updates? And then update this to the newest package version...

@dbast Good suggestion! But instead of branching from an old commit (since that would have used conda-build 2), I replaced the build requirements with those from the original recipe

https://github.com/conda-forge/r-rodbc-feedstock/blob/87e2d5a48fabfee5d69477dba8ac075856ef4678/recipe/meta.yaml#L29-L34

**Comment by jdblischak** [comment]
> Might it help to use linux-anvil rather than linux-anvil-comp7?

@dpryan79 Thanks for the suggestion! I've also pushed this change

**Comment by h-vetinari** [comment]
Woohoo, it passed! Thanks a lot everyone for the team effort! :)

**Comment by jdblischak** [comment]
> Woohoo, it passed! Thanks a lot everyone for the team effort! :)

Great! It appears that using the linux-anvil image did the trick, because the earlier commit had still failed. I'm going to update the CI scripts to pull linux-anvil (in the previous run, they pulled linux-anvil-comp7, only to have to pull linux-anvil during the `docker run` call).

```
+ docker run -it -v /home/circleci/test/recipe:/home/conda/recipe_root:ro,z -v /home/circleci/test:/home/conda/feedstock_root:rw,z -e CONFIG -e BINSTAR_TOKEN -e HOST_USER_ID -e UPLOAD_PACKAGES condaforge/linux-anvil bash /home/conda/feedstock_root/.circleci/build_steps.sh
Unable to find image 'condaforge/linux-anvil:latest' locally
latest: Pulling from condaforge/linux-anvil
```

https://circleci.com/gh/jdblischak/r-rodbc-feedstock/10

**Comment by jdblischak** [comment]
Alright, all the tests passed again. Any objections to merging this PR?

**Pull request merged**
