### PR TITLE
Update to version 1.3-15, update recipe

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
@bgruening Ready to merge. Thx.

**Comment by dbast** [comment]
@bgruening Ready to merge. Thx.

**Comment by bgruening** [comment]
Daniel can I wait with those a little bit? The Queue is full atm and we try to push the GCC7 over the line, which will, in turn, make all these double-build go away.

I will keep the tab open and merge when the queue is empty again, ok?

**Comment by dbast** [comment]
Yes, fine. I am anyway done with updates for now... not taking over the job of the bot ;) Need my time somewhere else ... 4 PRs to go: 2 already ready, 2 need some work... ~5 noarch pkgs to label (will collect and list them in the other issue).

This PR is particularly interesting as the last master builds partially failed.

**Comment by bgruening** [comment]
Oh I will miss you. Thanks for all your help!

I fixed the master branch already.

**Comment by dbast** [comment]
Thanks Björn. Very much appreciated! I am still in and contributing... Just being careful with my priorities at the moment.

**Pull request merged**
